apiVersion: v1
kind: Service
metadata:
  name: monitor-grafana-lb
  namespace: monitoring
spec:
  type: LoadBalancer
  ports:
  - port: 9091
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
